from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


DEFAULT_RECOVERABILITY_JSON = "data/recoverability_comparison_final/recoverability_unified_gru_with_scp_summary.json"
DEFAULT_COMPLEXITY_CSV = "data/complexity_stagepair_suite/pair_summary.csv"
DEFAULT_OUTPUT_CSV = "data/recoverability_comparison_final/integrated_stagepair_summary.csv"
INTERPRETATION_NOTE = (
    "higher ccc/pearson_r/scp_mean_coherence indicates stronger recoverability/support; "
    "lower nrmse/psd_distance/rms_relative_error/median_frequency_relative_error is better; "
    "higher delta_pe/delta_sampen indicates stronger complexity reduction, "
    "not necessarily greater useful information loss"
)
RANKING_NOTE = "axis-specific ranks only; no final information-loss rank is assigned in v1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the integrated recoverability + coherence + complexity summary CSV.")
    parser.add_argument(
        "--recoverability-json",
        default=DEFAULT_RECOVERABILITY_JSON,
        help="Unified GRU recoverability summary augmented with coherence support.",
    )
    parser.add_argument(
        "--complexity-csv",
        default=DEFAULT_COMPLEXITY_CSV,
        help="Pair-level complexity summary CSV generated by run_complexity_stagepair_suite.py.",
    )
    parser.add_argument(
        "--output-csv",
        default=DEFAULT_OUTPUT_CSV,
        help="Output CSV path for the integrated pair-wise summary.",
    )
    return parser.parse_args()


def load_json(path: str | Path) -> dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as file:
        return json.load(file)


def extract_recoverability_rows(payload: dict[str, Any]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    pair_results = payload.get("pair_results", [])
    for pair_result in pair_results:
        if "model_free_auxiliary_metric" not in pair_result:
            raise ValueError(
                "Unified recoverability JSON is missing model_free_auxiliary_metric. "
                "Run augment_recoverability_with_scp.py first."
            )

        recoverability_pair = str(pair_result["stage_pair"])
        condition_stage, target_stage = recoverability_pair.split("->", 1)
        suite_summary = pair_result["selected_model_analysis"]["suite_summary"]["fold_summary_mean"]
        coherence_summary = pair_result["model_free_auxiliary_metric"]["pair_summary"]["summary_mean"]
        rows.append(
            {
                "pair_order": len(rows),
                "recoverability_pair": recoverability_pair,
                "condition_stage_from_recoverability": condition_stage,
                "target_stage_from_recoverability": target_stage,
                "ccc": float(suite_summary["ccc"]),
                "nrmse": float(suite_summary["nrmse"]),
                "pearson_r": float(suite_summary["pearson_r"]),
                "psd_distance": float(suite_summary["psd_distance"]),
                "rms_relative_error": float(suite_summary["rms_relative_error"]),
                "median_frequency_relative_error": float(suite_summary["median_frequency_relative_error"]),
                "scp_mean_coherence": float(coherence_summary["scp_mean_coherence"]),
            }
        )
    return pd.DataFrame(rows)


def add_rank(df: pd.DataFrame, source_col: str, rank_col: str) -> None:
    df[rank_col] = (
        df[source_col]
        .rank(method="min", ascending=False, na_option="bottom")
        .astype(int)
    )


def main() -> None:
    args = parse_args()
    recoverability_df = extract_recoverability_rows(load_json(args.recoverability_json))
    complexity_df = pd.read_csv(args.complexity_csv)

    merged = recoverability_df.merge(complexity_df, on="recoverability_pair", how="inner", validate="one_to_one")
    if len(merged) != len(recoverability_df):
        missing = sorted(set(recoverability_df["recoverability_pair"]) - set(merged["recoverability_pair"]))
        raise ValueError(f"Complexity summary is missing recoverability pairs: {missing}")

    if not (
        (merged["condition_stage_from_recoverability"] == merged["condition_stage"])
        & (merged["target_stage_from_recoverability"] == merged["target_stage"])
    ).all():
        raise ValueError("Recoverability stage labels do not match complexity stage labels.")

    merged = merged.drop(columns=["condition_stage_from_recoverability", "target_stage_from_recoverability"])
    merged["interpretation_note"] = INTERPRETATION_NOTE
    merged["ranking_note"] = RANKING_NOTE

    add_rank(merged, "delta_pe_mean", "rank_by_delta_pe")
    add_rank(merged, "delta_sampen_mean", "rank_by_delta_sampen")
    add_rank(merged, "ccc", "rank_by_ccc")
    add_rank(merged, "scp_mean_coherence", "rank_by_scp_mean_coherence")

    merged = merged.sort_values("pair_order").drop(columns=["pair_order"]).reset_index(drop=True)
    output_path = Path(args.output_csv)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(output_path, index=False)
    print(f"Saved integrated stage-pair summary CSV to: {output_path.resolve()}")


if __name__ == "__main__":
    main()
